{% set version = "3.6.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotmo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plotmo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plotmo/plotmo_{{ version }}.tar.gz
  sha256: cde33a8ec558b12d8e11d7d0531e73f6678a25ee589b79897d2fc425a3fd353c

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula >=1.2_3
    - r-teachingdemos
    - r-plotrix
  run:
    - r-base
    - r-formula >=1.2_3
    - r-teachingdemos
    - r-plotrix

test:
  commands:
    - $R -e "library('plotmo')"           # [not win]
    - "\"%R%\" -e \"library('plotmo')\""  # [win]

about:
  home: http://www.milbo.users.sonic.net
  license: GPL-3.0-only
  summary: Plot model surfaces for a wide variety of models using partial dependence plots and other techniques. Also plot model residuals and other information on the model.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: plotmo
# Version: 3.5.5
# Title: Plot a Model's Residuals, Response, and Partial Dependence Plots
# Author: Stephen Milborrow
# Maintainer: Stephen Milborrow <milbo@sonic.net>
# Depends: R (>= 3.4.0), Formula (>= 1.2-3), plotrix, TeachingDemos
# Description: Plot model surfaces for a wide variety of models using partial dependence plots and other techniques. Also plot model residuals and other information on the model.
# Suggests: C50 (>= 0.1.0-24), earth (>= 5.1.0), gbm (>= 2.1.1), glmnet (>= 2.0.5), glmnetUtils (>= 1.0.3), MASS (>= 7.3-45), mlr (>= 2.12.1), neuralnet (>= 1.33), partykit (>= 1.2-2), pre (>= 0.5.0), rpart (>= 4.1-10), rpart.plot (>= 2.1.0)
# License: GPL-3
# LazyData: yes
# URL: http://www.milbo.users.sonic.net
# NeedsCompilation: no
# Packaged: 2019-06-27 19:16:00 UTC; milbo
# Repository: CRAN
# Date/Publication: 2019-06-27 20:20:03 UTC
