appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Loq2/ixK79E6tg2JJVvnCl1U8e7AMGLMZoYvn7M6ptVKOlDxOIwNGY1hTMTXFZqIMokNWBpCa/X+JtuUmuEnjnmA4NQXe+ODrrZW9a9A9pxCtB1Plb9fTjwudwQpVs8DWItUOXIUUFRNtAtTHeSYU6uGoiM2TwbwCCzGurN/Gre0Vj0KgJQKli9AKkNljIxNexEgCYJVatj0RRE3RP3jhxeROHll+bKdrD3hD5JBCsarPC2vgz+o2tZu8mT8Hw8PwNj7MgpOkjLjYeXzIcZE+g/0naOnytv8E7F7dLp7rE/LygBlK5jYFa+qMwpKRxIowwW6/uVSrCkvctmUdltUTZEUWiK/vTVHRFGzPC3r9e/hQseHu0EwsEx/XglcD9Wy1AvrDcIhL35Gd5nOMUjSnBqDlAHVx92NCvQZjpTh/cK7V5kJxgOo8vATdxUnSNScIIXrqc0MPbBf8RNK8WEL5FFf1ZZ7pvNoVVrHsukPx264pL9eVA/HyiOYF23ovB7RNh922+aMOXIJrLceHwX0aL/wputhsGBhXLhBNtO/T3szp4dI3U1xL/VhYeWuR89AggcDsnBSszT6oL6W8gIlDH1k3kWHYIlMQAd2S16/8gm08HknsDi1C5Dt7B8tKJVgaHzAxBHY5glvqZXbggjbReu6rRdgNsB5Js9ZJdH/NL8=}
bot:
  automerge: true
